name: Deploy to Netlify

on:
    push:
        branches:
            # - master
            - deploy
jobs:
    deploy-to-netlify:
        runs-on: ubuntu-latest
        steps:
            -
                # Ref: https://github.com/marketplace/actions/netlify-deploy
                name: Deploy
                uses: jsmrcaga/action-netlify-deploy@v2.1.0
                with:
                    NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
                    NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
                    NETLIFY_DEPLOY_TO_PROD: true
                    NETLIFY_DEPLOY_MESSAGE: "Deploy from: ${{ github.ref }}"