name: Deploy to Netlify

on:
    push:
        branches:
            # - master
            - deploy
jobs:
    deploy-to-netlify:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [20.x]
        steps:
            -
                name: Checkout source
                uses: actions/checkout@v4
            -
                name: Use Node.js ${{ matrix.node-version }}
                # Ref: https://github.com/actions/setup-node
                uses: actions/setup-node@v4
                with:
                    node-version: ${{ matrix.node-version }}
            -
                name: Run tests
                run: |
                    npm install
                    npm test
            -
                name: Deploy
                # Ref: https://github.com/marketplace/actions/netlify-deploy
                uses: jsmrcaga/action-netlify-deploy@v2.1.0
                with:
                    NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
                    NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
                    NETLIFY_DEPLOY_TO_PROD: true
                    NETLIFY_DEPLOY_MESSAGE: "Deploy from: ${{ github.ref }}"