name: Run Test Cases
on:
    push:
        branches:
            # No need for "master" since "Deploy to Netlify" already handles its testing.
            - next-version
            - multilanguage
jobs:
    run-test-cases:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [20.x]
        steps:
            -
                name: Checkout source
                uses: actions/checkout@v4
            -
                name: Use Node.js ${{ matrix.node-version }}
                uses: actions/setup-node@v4
                with:
                    node-version: ${{ matrix.node-version }}
            -
                name: Run tests
                run: |
                    npm install
                    npm test