name: Run Tests and Deploy

on:
    push:
        branches:
            - master
            - next-version
        tags:
            - 'v[0-9]+.*'
            - version-*

jobs:
    print-github-ref:
        runs-on: ubuntu-latest
        steps:
            -
                name: Print branch/tag ref (${{ github.ref_name }})
                run: echo "Ref = ${{ github.ref }}"
    run-tests:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [20.x]
        steps:
            -
                name: Checkout source
                uses: actions/checkout@v4
            -
                name: Use Node.js ${{ matrix.node-version }}
                # Ref: https://github.com/actions/setup-node
                uses: actions/setup-node@v4
                with:
                    node-version: ${{ matrix.node-version }}
            -
                name: Run tests
                run: |
                    npm install
                    npm test
    deploy-to-netlify:
        if: github.ref_name == 'master'
        needs: run-tests
        runs-on: ubuntu-latest
        steps:
            -
                name: Checkout source
                uses: actions/checkout@v4
            -
                name: Deploy
                # Ref: https://github.com/marketplace/actions/netlify-deploy
                uses: jsmrcaga/action-netlify-deploy@v2.1.0
                with:
                    NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
                    NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
                    NETLIFY_DEPLOY_TO_PROD: true
                    NETLIFY_DEPLOY_MESSAGE: "Deploy from: ${{ github.ref }}"